const santaMessages: string[] = [
    "Oh, you found the limited-edition whiskey for Uncle Bob! This will surely make the holidays... blurry.",
    "Great job finding the karaoke machine! Aunt Susan's neighbors are going to *love* you for this.",
    "Ah, the drum set for little Timmy! He'll be thrilled, but his parents might need earplugs. Or therapy.",
    "You found the scented candles! Now Grandma can make her house smell like 37 types of lavender. Delightful!",
    "Oh look, the VR headset for Dad! He might come back to reality around Easter.",
    "Nice work finding the skateboard! Let’s hope Cousin Mike remembers he’s 42 now.",
    "The box of chocolates! Mom’s secret stash of 'self-care' is back on track.",
    "Ah, the pogo stick for Lucy! The floors might not survive, but she will have a blast!",
    "You found the designer purse! Aunt Carol will look classy while she complains about her back pain.",
    "The electric guitar for Alex! Time for some rock and roll... and some noise complaints.",
    "You got the espresso machine! Let's prepare for sleepless nights and jittery mornings.",
    "Perfect! The book of dad jokes. Prepare for the groans of an entire household.",
    "Ah, the DIY craft set for your niece! Her parents are going to love the glitter... *everywhere*.",
    "Great find! A gift card for a spa day. Too bad it doesn’t come with free babysitting.",
    "You found the blender! Now Uncle Ted can make margaritas no one asked for.",
    "The socks with wild patterns! Because nothing says 'fun' like hidden chaos in your shoes.",
    "Oh look, a board game! Cue the family bonding and inevitable passive-aggressive arguments.",
    "A fancy new watch for Grandpa! He still won't know how to set it, though.",
    "Nice work! The wine set for Aunt Marie. Holiday survival kit: complete.",
    "Ah, the vintage record player! Now Dad can lecture everyone about 'real music.'",
    "You found the roller skates! Let’s hope Cousin Jenna’s knees are still insured.",
    "The yoga mat for Aunt Linda! She'll meditate, stretch, and then complain about her hips.",
    "A plush robe for Mom! Now she can *officially* lounge in style while ignoring everyone.",
    "Oh, a sci-fi novel for Jeff! Prepare for hours of plot recaps you didn’t ask for.",
    "The remote-controlled car! Now Dad has something else to crash into the furniture.",
    "Great job! You found the jigsaw puzzle. Family time or family feud? Let’s find out!",
    "Ah, the perfume set for Aunt Patty! She’ll love it, and so will everyone within a 10-foot radius.",
    "The novelty mug! Because Dad really needed a cup that says, 'World's Okayest Dad.'",
    "You found the fitness tracker! Let’s see how long until it's 'accidentally' left in a drawer.",
    "The cookbook! Time for some experimental dishes... and a backup pizza delivery plan.",
    "You found the snow globe! Now Aunt Betty can shake a winter wonderland without leaving the couch.",
    "Ah, the cocktail shaker set! Uncle Joe’s about to rediscover the 'art' of mixing drinks—and disasters.",
    "The hot sauce gift box! Someone’s taste buds are about to file for early retirement.",
    "A set of bath bombs! Now your sister can feel like she’s relaxing in a fizzy rainbow... until the kids bang on the door.",
    "You found the beard grooming kit! Time to turn Cousin Steve’s 'wild woodsman' look into 'confused hipster.'",
    "Ah, the Bluetooth speaker! Get ready for holiday classics with a side of questionable volume control.",
    "The yoga DVD set! Because nothing says relaxation like falling over during downward dog.",
    "Oh, the retro video game console! Dad's about to show the kids how he 'used to dominate'... 30 years ago.",
    "You found the astronomy kit! Now everyone gets to freeze outside while pretending to know constellations.",
    "The pet sweater! Your cat's going to love you... or plot revenge in style.",
    "Nice work! The personalized calendar. Grandma can now schedule *everyone’s* lives.",
    "Ah, the noise-canceling headphones! Perfect for surviving family gatherings without starting a feud.",
    "You found the fitness DVD! Cousin Mike will start tomorrow... or maybe next year.",
    "The inflatable hot tub! Because what’s better than a lukewarm pool in the middle of winter?",
    "Ah, the fancy teapot! Now Aunt Jane can pretend she’s hosting a royal tea party. Pinkies up!",
    "The scented hand soap set! Because who doesn't need a bathroom that smells like 'Ocean Breeze with Vanilla Twilight'?",
    "A magic kit for Billy! Let’s hope he learns to make his messes disappear.",
    "You found the calendar full of motivational quotes! Perfect for making everyone feel vaguely guilty.",
    "The electric massager! Because sometimes the holidays are a real pain in the neck.",
    "The heated blanket! Now Grandma can roast herself like a marshmallow all winter long.",
    "You got the fancy wine opener! Because struggling with corkscrews is *so* last year.",
    "Ah, the adult coloring book! Stress relief meets the frustration of staying inside the lines.",
    "You found the fishing gear! Dad will finally have another excuse to avoid chores.",
    "The candle-making kit! Now your sister can create fire hazards in *any* scent.",
    "The new drone! Prepare for 10 minutes of fun and 2 hours of finding where it crashed.",
    "Oh, the DIY home-brew kit! Get ready for beer that *might* be drinkable... or not.",
    "You found the gourmet popcorn set! Perfect for eating during movie night... or just because.",
    "The karaoke microphone! Aunt Linda's going to belt out tunes like she's at Madison Square Garden.",
    "Ah, the leather wallet! A classy way for Uncle Tom to carry around *just* coupons.",
    "The luxury bathrobe! Mom's about to level up her lounging game to pro status.",
    "You found the mystery puzzle! Grandma will enjoy piecing it together... until the dog eats a piece.",
    "The karaoke microphone for Aunt Janet! Her *Broadway debut* is happening in the living room tonight.",
    "The superhero cape for Timmy! He'll save the day... or at least attempt to jump off the couch.",
    "Ah, the prank gift box! Dad's about to give a present that confuses everyone, including himself.",
    "The glow-in-the-dark puzzle for Cousin Mark! Because who needs lights when frustration glows?",
    "You found the digital photo frame! Perfect for Mom to display *way too many* vacation photos.",
    "The retro record player for Uncle Dave! He'll tell everyone vinyl sounds better, and everyone will pretend to agree."
  ];

  export { santaMessages };